apiVersion: v1
kind: Service
metadata:
  name: ocelot
  labels:
    app: ocelot
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  selector:
    app: ocelot
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ocelot
  name: ocelot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ocelot
      name: ocelot
    spec:
      containers:
      - name: ocelot
        imagePullPolicy: IfNotPresent
        image: registry.yx.com/ctc/ocelot:1.0.0
      nodeSelector:
        beta.kubernetes.io/os: linux